
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Inspinia_MVC5_SeedProject.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CarAd
{

    public int adId { get; set; }

    public Nullable<short> year { get; set; }

    public Nullable<int> kmDriven { get; set; }

    public string color { get; set; }

    public string fuelType { get; set; }

    public int carModel { get; set; }

    public Nullable<short> noOfOwners { get; set; }

    public Nullable<int> registeredCity { get; set; }

    public string transmission { get; set; }

    public string assembly { get; set; }

    public Nullable<int> engineCapacity { get; set; }



    public virtual Ad Ad { get; set; }

    public virtual City City { get; set; }

    public virtual CarModel CarModel1 { get; set; }

}

}
