
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Inspinia_MVC5_SeedProject.Models
{

using System;
    using System.Collections.Generic;
    
public partial class City
{

    public City()
    {

        this.AdsLocations = new HashSet<AdsLocation>();

        this.popularPlaces = new HashSet<popularPlace>();

        this.CompanyOffices = new HashSet<CompanyOffice>();

        this.Companies = new HashSet<Company>();

        this.CarAds = new HashSet<CarAd>();

        this.BikeAds = new HashSet<BikeAd>();

    }


    public int Id { get; set; }

    public string addedBy { get; set; }

    public System.DateTime addedOn { get; set; }

    public string updatedBy { get; set; }

    public Nullable<System.DateTime> updatedOn { get; set; }

    public string cityName { get; set; }

    public string status { get; set; }



    public virtual ICollection<AdsLocation> AdsLocations { get; set; }

    public virtual ICollection<popularPlace> popularPlaces { get; set; }

    public virtual ICollection<CompanyOffice> CompanyOffices { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }

    public virtual AspNetUser AspNetUser1 { get; set; }

    public virtual ICollection<Company> Companies { get; set; }

    public virtual ICollection<CarAd> CarAds { get; set; }

    public virtual ICollection<BikeAd> BikeAds { get; set; }

}

}
