//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.JobSkills = new HashSet<JobSkill>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string addedBy { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual ICollection<JobSkill> JobSkills { get; set; }
    }
}
